### PR TITLE
bump object-store to 0.10

### PR DESCRIPTION
**Pull request by kylebarron**

### CODE REVIEW

**Comment by kylebarron** [comment]
Actually looks like there were some changes around multipart uploads in object-store 0.10. I don't have the time right now to fix those

**Comment by kylebarron** [comment]
@H-Plus-Time is there some way to easily bump to object-store 0.10? I'm trying to upgrade geoarrow-rs to use arrow/parquet 52, and parquet 52 uses object store 0.10, so I need to update this object-store-wasm to also use object-store 0.10

**Comment by kylebarron** [comment]
I commented out multi part uploads for S3 but otherwise this branch compiles on object-store 0.10, which is good enough for geoarrow-rs to depend on this branch

**Comment by H-Plus-Time** [comment]
Oops, yes, I've let this one languish a tad. Yeah, I know of no-one depending on it for Multi-Part (and it's not as if there aren't other options), LGTM.

**Comment by H-Plus-Time** [comment]
> Actually looks like there were some changes around multipart uploads in object-store 0.10. I don't have the time right now to fix those

Oh. Oh dear. I really need a good way to distinguish between bot notifications and ones from actual people 😬

**Comment by kylebarron** [comment]
No worries! I've been taking a bit of a break!

**Pull request merged**
